# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Chorok-BE_new/ # 프로젝트 이름
#    destination: /home/ubuntu/playground_logging/ # 프로젝트 이름
    overwrite: yes


permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu


hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/health_check.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 180
      runas: ubuntu